spring:
  datasource:
      url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  file: D:/logs/sql/sql_log.log
  level:
    org.springfromework.web: debug



